### ISSUE TITLE
Cannot build Linux version

### ISSUE THREAD

**Issue by quimgil** [git-moss/ConvertWithMoss#1]
I wonder whether anyone has succeeded building the Linux version apart from Moss. :)

First, `sh ./jpackage-linux.sh` makes mvn complain about the location of JAVA_HOME. After looking everything in my system, I realized that the problem is this line in the script:

`export JAVA_HOME=/home/mos/java/jdk-16+36/`

After commenting this line, the script starts compiling but ends with errors:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: invalid target release: 16
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  56.406 s
[INFO] Finished at: 2021-07-25T23:34:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project sampleconverter: Compilation failure
[ERROR] error: invalid target release: 16
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

At this point, I don't know what to do. I only wanted to try this cool converter, not to embark in Java debugging (I have no clue about Java).

Help, please!

**Comment by git-moss** [comment]
The easiest solution is to download the installer from my homepage: http://www.mossgrabers.de/Software/SampleConverter/SampleConverter.html

Regarding your issue you need to point JAVA_HOME to a JDK 16 (the JRE is also not enough) install on your system. It seems you have an older version installed which gets picked up.
