### ISSUE TITLE
[Feature Request] MPC Keygroup: Concatenate samples into one big file

### ISSUE THREAD

**Issue by Loadus** [git-moss/ConvertWithMoss#10]
Creating MPC Keygroups generates the .xpm file and a huge stack of separate sample files which clutter the folder (and make browsing for instruments slower on the standalone boxes). I suggest concatenating all the instrument samples into one huge sample file and just marking the sample frame position into the instrument file.

**Comment by git-moss** [comment]
Interesting but not sure if I will ever tackle this. Do you have a specification of the file format?

**Comment by Loadus** [comment]
On my own scripts I just create a WAV file and combine all the data from the short samples into the big one. Relatively straightforward. : )

**Comment by git-moss** [comment]
If all the samples have the same resolution and bit rate :-)
Again: do you have a spec of the necessaty fields?

**Comment by Loadus** [comment]
Yes, concatenation would fail with error if one or more files would be in different format (very rare case, but possible).

I don't have any specs to give, I usually take the Wave file format from the first sample and just clump the data in there. In the MPC file, I add the accumulated frame amount (the sum of already concatenated Wave file frames) to
`<SliceStart></SliceStart>`
and
`<SliceEnd></SliceEnd>`
and
`<SliceLoop></SliceLoop>`

You can grab an example file (and sample) from here >> https://drive.google.com/file/d/1MTrrb8KQVZ8XNPI5xl6E-rCwtRanu5eP/view?usp=sharing

**Comment by spurkopf** [comment]
Sorry if I meddle here. I don't know if that would work for drum instruments. - but ConvertWith Moss offers MPC keygroups that mostly need loop points, and I assume MPC only supports one loop per .wav.

**Comment by git-moss** [comment]
Will close this until there will be a publicly available documentation available.

**Comment by Loadus** [comment]
> Sorry if I meddle here. I don't know if that would work for drum instruments. - but ConvertWith Moss offers MPC keygroups that mostly need loop points, and I assume MPC only supports one loop per .wav.

MPC programs support loop per slice, I have done this on my own export scripts. Very easy to do.
