### ISSUE TITLE
Conversion from MPC Keygroup to Bitwig does not work.

### ISSUE THREAD

**Issue by sequoi** [git-moss/ConvertWithMoss#12]
@git-moss 

Running 5.1 - Converting from MPC Keygroup into Bitwig does not work for me on Windows 10. When I press convert, all files are reported as "Done" and everything seems to be fine, but when I try to load the patch in Bitwig, then I am getting this error (screenshot attached):

**Could not read metadata: Mandatory RIFF chunk data missing.**

https://i.postimg.cc/Z55FHkTS/2022-07-06-07-53-06-Audio.jpg

edit: I tried to convert (just in case) from MPC into SFZ and that seems to be working. I mean samples are loaded fine so I believe the converter is working fine, it's just that Bitwig output is broken.

**Comment by git-moss** [comment]
Seems the WAV file is broken or damaged. I also noted that a few of the files in the MPC library have such an issue.
To fix this try to open the file in an audio editor and save it again.

**Comment by sequoi** [comment]
Hello, Mister Moss. Thank you for your kind response.  

No, if you mean by the source files being damaged then files are not damaged in any case. Not mine or anyone else's.

I mean I just tried to convert a "commercial" MPC library into Bitwig with the same outcome. 

What I am pointing out is this:

1. I doubt a commercial library would ship broken or damaged samples.2
2. when I copy samples from those libraries shipped in MPC format and place them into some folder on my computer - the same Bitwig is seeing those samples in the browser just fine and can load them in a session (or sampler) just fine.

So Manually loading those samples is fine by Bitwig. They seems to be broken only after conversion.

Also converting the same samples into SFZ format with your converter and loading in Bitwig is working. It just seems that Bitwig file conversion is not working because only that format is giving me an error. Ironically it's the only output format (Bitwig that is) in which I am interested.

I checked that. I also tried to install 5.0 and it's the same outcome. Let me know if you can advice me on trying anything else.

**Comment by git-moss** [comment]
That's strange since the files should only be zipped and not altered. But could be that mono to stereo file conversion is involved.
Could you send me one example source file?

**Comment by git-moss** [comment]
As I assumed the file has an incorrect header. That is what Wavelab reports:
![Screenshot 2022-07-06 114821](https://user-images.githubusercontent.com/3090132/177523044-70239711-a149-460b-b781-9f888f3f3f24.png)
Many programs simply carry on but Bitwig seems not to accept it. Simply resaving the file should fix it. E.g. you can use Reaper for doing this in a batch if it concerns many files.

**Comment by sequoi** [comment]
That's interesting. You are on to something but I beg to differ. Allow me to explain myself.

I did what you asked me. Resaved sample in a different editor. And now conversion works fine. 

However, your error is revealed only in Wavelab and not everywhere else. 

I tried Audition, Izotope RX, Presonus, Live, Cubase, Reason, and FL Studio. So a sample is loaded across numerous DAW applications and audio editors. No error whatsoever. I tried to load a sample on my old and trusty AKAI S6000 hardware, no error message.

In fact, what is an interesting fact is that the pre-conversion sample is loading just fine even in Bitwig itself.

What is **even more interesting** is that the same pre-converted sample (supposedly with bad headers) can be manually loaded in Bitwig Sampler, saved as a Bitwig Sampler file, through the very same Bitwig, and this very same supposedly buggy sample is loading later in Bitwig sampler just fine. When saved in the very same format your converter is saving to. 

So when I save this very same supposedly bad sample in Bitwig itself, as Bitwig Sampler preset - it is loading fine.

It looks like the sample is supposedly damaged or that the supposed error is revealed only after it goes through your own conversion tool and is saved as a Bitwig Sampler format file. 

Even your SFZ tool outputs the same file and it's working.

Note that I fully understand this is free software and is supported by you in goodwill. 

I am not complaining about your effort. I am explaining that it seems very irrational for me to accept that samples are wrong while in fact 

a: the very same sample is working on countless audio editors and DAWs, 
b: in fact it's even working in Bitwig itself and when saved from Bitwig in the very same format that you're trying to generate - it is working fine

Sorry but it sounds like your converter and its Bitwig output is the one to be blamed for the error. 

I think you could work on the output format because not everyone has access to commercial batch converters and people should not pay for additional DAW apps only to be able to use your converter.  And besides that, I tried to convert samples from different vendors such as AKAI itself, mpc-samples, E-lab, Wave-Alchemy and so on.

It really seems hard to accept that all these sample vendors are wrong when Wavelab is correct.

Thanks for your time. Much appreciated.

**Comment by sequoi** [comment]
I'll try again as well. 

1. I realized that the file is indeed "broken". That's why I said that when I resaved it with a batch converter as per your instruction - your converter indeed worked.

2. You are completely missing a point. No one is debating that the file may have some metadata error. What I am saying is:
- All vendors seem to have such errors in their libraries. Not just AKAI. I've run and wasted a lot of time with this today and this is not AKAI-related. It seems the error is so mandatory that it is slipping into libraries provided by the largest online shops.


The error may be real but it's so mandatory that no one cares for it, thus it's working in every DAW or audio editor in existence. It is even ignored by Bitwig itself.

I am unsure what you mean by multisample or which version you are working at, as I said I can load a supposedly broken sample in Bitwig and save it in Bitwig natural Sampler format and it's working fine. Yes, even multi-samples.

It only seems to be affecting your own converter. Even when there is a single sample (not a multisample patch). I would accept this issue as a nonsolvable issue but your own converter spits out SFZ files which are then normally read in Bitwig. 

What I am failing at is probably a language barrier and not direct whining or critics of your work. I am not saying you are incompetent or something like that. English is not my native so perhaps I am sounding harsh? This is not what I wanted.

You need to realize that it is very unlikely that people will use your converter to convert 3 or 4 samples. They will want to use it to convert thousands of samples in one go. 

In the end, it doesn't matter, I am not here to upset you. I wanted to report my findings because I didn't see anything like that reported on KVR on both threads (old one and new one). My work is not dependent on this converter thus I merely wanted to report this to you.

I sincerely wish you the best.
