### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by Superfly-Johnson** [git-moss/ConvertWithMoss#13]
Hello! I've been looking at this project (since I needed a tool to convert dslibrary files to standard sf2) and I noticed there's no build documentation. 

Any headers on how I could build the project?

**Comment by git-moss** [comment]
If you just want to use it, download it from my homepage: https://www.mossgrabers.de/
But sf2 is not supported as destination.

The project is using Maven, so "mvn install" will do it. See the (Windows) command line files in the repo.

**Comment by Superfly-Johnson** [comment]
Thank you very much. 

I was actually looking to package it for NixOS.

**Comment by git-moss** [comment]
Then look at the different jpackage scripts.
