### ISSUE TITLE
MPC keygroup to KSF/KMP issue

### ISSUE THREAD

**Issue by Potreba** [git-moss/ConvertWithMoss#21]
When converting multiple velocities samples inside KSF overwrite each other. Instead of creating new folders it just overwrites samples

**Comment by git-moss** [comment]
Can you provide me an example for testing?

**Comment by Potreba** [comment]
[EP virgin.zip](https://github.com/git-moss/ConvertWithMoss/files/11044097/EP.virgin.zip)

Here's a zip for you to try out. Try extracting and converting to KSF/KMP. It will create 4 layers, but each layer has identical sample names (default KSF0000001 - KSF00000012) and thus overwrites each consecutive layer. I've worked around it by exporting each layer as separate program to its own folder, but it not ideal

**Comment by git-moss** [comment]
Thanks, will have a look.

**Comment by git-moss** [comment]
Will be fixed in the next update!
