### ISSUE TITLE
Add support for Blackbox autosampler format

### ISSUE THREAD

**Issue by Zaat** [git-moss/ConvertWithMoss#23]
Feature request:

Be able to convert from (maybe to also) the Blackbox (1010music) autosampler which is a folder of WAV files. Although I think you could do it through the WAV file format conversion, it wasn’t straightforward for me. 

It’d be nice to have a template for it so you could simply select it for conversion. Despite it being fairly straightforward it’d be straightforward to implement and less work on the user part. 

The multi samples are stored in a folder per instrument and look like this:

![IMG_8241](https://github.com/git-moss/ConvertWithMoss/assets/16344035/23313ef3-9412-4846-be97-ba4559c6c2fa)

The first value is velocity and the second the MIDI number.

BTW, If there is a workaround for now does anyone have an idea how exactly with this MIDI note number? Thanks.

**Comment by git-moss** [comment]
Don't think that this will happen (don't have a Blackbox) but will leave it open as a reminder.

**Comment by benzkji** [comment]
@Zaat aren't there some .xml files lying around? They would contain the rest of the information, and would (hopefully) be quite easy to read. Will dig in if having some time...

**Comment by git-moss** [comment]
Support was added in ConvertWithMoss 7.4.
