### ISSUE TITLE
HISE format support

### ISSUE THREAD

**Issue by luxaritas** [git-moss/ConvertWithMoss#24]
First off, many thanks for this awesome software - I'm grateful for the possibility to take advantage of sounds I may not have been able to use otherwise.

I was curious if you had any thoughts on supporting HISE (https://hise.dev/, https://github.com/christophhart/HISE), particularly as an output format. DecentSampler has gotten a fair amount of attention for being free software and an open sampler format, but the benefit of HISE (aside from being open source) is that it is much more advanced, and could potentially support a broader featureset from the input format (if not for features that could be automatically converted - NKI's group insert fx comes to mind - HISE supports scripting which may be necessary to reimplement some advanced features)

**Comment by git-moss** [comment]
I had a look in the past but it is a bit hard to get into. Where is the sample format specified?

**Comment by luxaritas** [comment]
HISE has a "monolith" codec called ch1/HLAC which I believe you can find the impementation of [here](https://github.com/christophhart/HISE/blob/d3f364f5c2832770a8bade634607e0f70b55f9df/hi_lac/hlac/HiseLosslessAudioFormat.cpp), but the simpler option would be the default one, which is to just have throw `wav` files in the `Samples` folder of the HISE project. Most metadata are just XML files, which you can find some examples of at https://github.com/christophhart/HISE/tree/d3f364f5c2832770a8bade634607e0f70b55f9df/extras

**Comment by git-moss** [comment]
Will not be supported.
