### ISSUE TITLE
Issue with text label display on new tabs in v7.3

### ISSUE THREAD

**Issue by g4z** [git-moss/ConvertWithMoss#26]
hi.

the latest 7.3 version has a problem for me where it is not displaying any text label on the new tabs. see screenshot.

i'm running on an Ubuntu 22.04.3 LTS and have installed `convertwithmoss_7.3.0-1_amd64.deb` (previous 7.2 worked fine, obviously didn't have the same tabs).

perhaps i'm missing some font rendering library or something?
any idea how i can make this work correctly. 
i really want to use the new TAL sampler support...

![image](https://github.com/git-moss/ConvertWithMoss/assets/16230360/eb34fadd-d443-41f7-8041-15db8e34f2a7)

thanks

**Comment by git-moss** [comment]
Thanks for reporting! Will be fixed in the next update!
