### ISSUE TITLE
build fails 7.3

### ISSUE THREAD

**Issue by toadzrock** [git-moss/ConvertWithMoss#28]
The deb build fails with the following error message:

/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
dpkg-deb: error: archive 'convertwithmoss_7.3.0-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive convertwithmoss_7.3.0-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 convertwithmoss_7.3.0-1_amd64.deb

I have tar, zstd, and libzstd-dev installed on my system. (AVlinux, based on Debian 11)

Any clues?

**Comment by git-moss** [comment]
Sorry, no idea. I only test on Ubuntu.
