### ISSUE TITLE
linux - convert KMP/KSF to anything produces no files

### ISSUE THREAD

**Issue by bsack23** [git-moss/ConvertWithMoss#30]
I built CWM on fedora linux in order to convert some KSF files to another format. I tried to convert .sf2 to .wav and it was successful, so i'm pretty sure the app works, but when i point it at a directory of .ksf files, it runs the analysis, but nothing else happens. There are no errors, just 

"Detecting and converting multi-samples...

Analyzing: /home/xxx/sounds/xxx

Finished."
Is there something else i can try to figure out what's going on?
thanks!
bill

**Comment by git-moss** [comment]
It is not intended to convert KSF only. You always need a KMP as a start.
