### ISSUE TITLE
SFZ flac

### ISSUE THREAD

**Issue by 9Skrip** [git-moss/ConvertWithMoss#31]
Hello. Thank you for this nice sample tool.
I wonder is it possible to add converter from SFZ wav instruments to SFZ flac instruments? Flac is widely used today between sample creators.
thanks in advance

**Comment by git-moss** [comment]
Will be in the next update.

**Comment by tank-trax** [comment]
Is flac import supported?

**Comment by git-moss** [comment]
Yes
