### ISSUE TITLE
NKI to Bitwig Multisample fail.

### ISSUE THREAD

**Issue by zebebop** [git-moss/ConvertWithMoss#32]
Hi perhaps a bug... a java issue, i don't know... 

Linux Mint (ubuntu) / CWM v7.5.0

---------------------------

Analyzing: /home/guru/Téléchargements/samples/00/Tama TS-305.nki
Detected Kontakt Container format (created with Kontakt 5.6.5.13) - Little-Endian.
Mapping: /Tama TS-305.nki
Using default volume envelope for category 'Drum Kit'.
Storing: /home/guru/Téléchargements/samples/bitwig/Tama TS-305.multisample
...Could not create multisample: Cannot invoke "de.mossgrabers.convertwithmoss.core.model.ISampleData.writeSample(java.io.OutputStream)" because the return value of "de.mossgrabers.convertwithmoss.core.model.ISampleZone.getSampleData()" is null

---------------------------

<?xml version="1.0" encoding="UTF-8"?>
<multisample name="Tama TS-305">
    <generator>ConvertWithMoss</generator>
    <category>Drum Kit</category>
    <creator>Kontakt</creator>
    <description/>
    <keywords>
        <keyword>KontaktInstrument</keyword>
    </keywords>
    <group color="d92e24" name="Kick"/>
    <group color="d92e24" name="Snares"/>
    <group color="d92e24" name="Hats"/>
    <group color="d92e24" name="Cymbals"/>
    <group color="d92e24" name="Toms"/>
    <sample file="bd-8.wav" gain="5.13" group="0" reverse="false" sample-start="0.000" sample-stop="26706.000">
        <key high="36" high-fade="0" low="36" low-fade="0" root="36" track="1.0000" tune="0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="bd-9.wav" gain="5.13" group="0" reverse="false" sample-start="0.000" sample-stop="24190.000">
        <key high="35" high-fade="0" low="35" low-fade="0" root="35" track="1.0000" tune="0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="rim.wav" gain="5.13" group="1" reverse="false" sample-start="0.000" sample-stop="35735.000">
        <key high="37" high-fade="0" low="37" low-fade="0" root="37" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="sd-org.wav" gain="5.13" group="1" reverse="false" sample-start="0.000" sample-stop="26016.000">
        <key high="38" high-fade="0" low="38" low-fade="0" root="38" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="hihat-2.wav" gain="5.13" group="2" reverse="false" sample-start="0.000" sample-stop="1889.000">
        <key high="44" high-fade="0" low="44" low-fade="0" root="44" track="1.0000"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="hihat-3.wav" gain="5.13" group="2" reverse="false" sample-start="0.000" sample-stop="10333.000">
        <key high="42" high-fade="0" low="42" low-fade="0" root="42" track="1.0000"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="oh-2.wav" gain="5.13" group="2" reverse="false" sample-start="0.000" sample-stop="19020.000">
        <key high="46" high-fade="0" low="46" low-fade="0" root="46" track="1.0000"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="crash.wav" gain="5.13" group="3" reverse="false" sample-start="0.000" sample-stop="27776.000">
        <key high="49" high-fade="0" low="49" low-fade="0" root="49" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="tom-3.wav" gain="5.13" group="4" reverse="false" sample-start="0.000" sample-stop="31435.000">
        <key high="45" high-fade="0" low="45" low-fade="0" root="45" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="tom-4.wav" gain="5.13" group="4" reverse="false" sample-start="0.000" sample-stop="30407.000">
        <key high="48" high-fade="0" low="48" low-fade="0" root="48" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
</multisample>

-------------------------------

result in destination file (zip extracted), the xml file and only 2 samples :

/home/guru/Téléchargements/samples/bitwig/Tama TS-305.multisample_FILES/multisample.xml
/home/guru/Téléchargements/samples/bitwig/Tama TS-305.multisample_FILES/bd-8.wav
/home/guru/Téléchargements/samples/bitwig/Tama TS-305.multisample_FILES/bd-9.wav

------------------------------

original 30 samples in source folder :

/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-1.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-2.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-3.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-4.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-5.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-6.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-7.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-8.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-9.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/bd-org2.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/click.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/click-2.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/crash.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/hihat-1.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/hihat-2.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/hihat-3.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/oh.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/oh-2.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/rim.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/sd-org.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tama2.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-1.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-2.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-3.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-4.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-5.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-6.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-7.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-org1.wav
/home/guru/Téléchargements/samples/00/Samples/Tama_TS-305/tom-org2.wav

**Comment by zebebop** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<multisample name="Tama TS-305">
    <generator>ConvertWithMoss</generator>
    <category>Drum Kit</category>
    <creator>Kontakt</creator>
    <description/>
    <keywords>
        <keyword>KontaktInstrument</keyword>
    </keywords>
    <group color="d92e24" name="Kick"/>
    <group color="d92e24" name="Snares"/>
    <group color="d92e24" name="Hats"/>
    <group color="d92e24" name="Cymbals"/>
    <group color="d92e24" name="Toms"/>
    <sample file="bd-8.wav" gain="5.13" group="0" reverse="false" sample-start="0.000" sample-stop="26706.000">
        <key high="36" high-fade="0" low="36" low-fade="0" root="36" track="1.0000" tune="0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="bd-9.wav" gain="5.13" group="0" reverse="false" sample-start="0.000" sample-stop="24190.000">
        <key high="35" high-fade="0" low="35" low-fade="0" root="35" track="1.0000" tune="0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="rim.wav" gain="5.13" group="1" reverse="false" sample-start="0.000" sample-stop="35735.000">
        <key high="37" high-fade="0" low="37" low-fade="0" root="37" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="sd-org.wav" gain="5.13" group="1" reverse="false" sample-start="0.000" sample-stop="26016.000">
        <key high="38" high-fade="0" low="38" low-fade="0" root="38" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="hihat-2.wav" gain="5.13" group="2" reverse="false" sample-start="0.000" sample-stop="1889.000">
        <key high="44" high-fade="0" low="44" low-fade="0" root="44" track="1.0000"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="hihat-3.wav" gain="5.13" group="2" reverse="false" sample-start="0.000" sample-stop="10333.000">
        <key high="42" high-fade="0" low="42" low-fade="0" root="42" track="1.0000"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="oh-2.wav" gain="5.13" group="2" reverse="false" sample-start="0.000" sample-stop="19020.000">
        <key high="46" high-fade="0" low="46" low-fade="0" root="46" track="1.0000"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="crash.wav" gain="5.13" group="3" reverse="false" sample-start="0.000" sample-stop="27776.000">
        <key high="49" high-fade="0" low="49" low-fade="0" root="49" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="tom-3.wav" gain="5.13" group="4" reverse="false" sample-start="0.000" sample-stop="31435.000">
        <key high="45" high-fade="0" low="45" low-fade="0" root="45" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
    <sample file="tom-4.wav" gain="5.13" group="4" reverse="false" sample-start="0.000" sample-stop="30407.000">
        <key high="48" high-fade="0" low="48" low-fade="0" root="48" track="1.0000" tune="-0.09"/>
        <velocity high="127" high-fade="0" low="1" low-fade="0"/>
    </sample>
</multisample>`

**Comment by git-moss** [comment]
Can you send me the source file?

**Comment by zebebop** [comment]
[sample.zip](https://github.com/git-moss/ConvertWithMoss/files/14628161/sample.zip)

Hi, the source file.

**Comment by git-moss** [comment]
It misses a sample file "rim.wav". ConvertWithMoss will output a more helpful error message in the next update.
