### ISSUE TITLE
https://www.mossgrabers.de/Software/ConvertWithMoss/ConvertWithMoss.html is down?

### ISSUE THREAD

**Issue by saynotohugs** [git-moss/ConvertWithMoss#33]
Sorry I'm not a developer, but how do I install (on a mac) when the download link is down?

Hope it's ok to ask :) 

Thanks

**Comment by sequoi** [comment]
It is ok to ask. I remember getting confused the first time when I visited Github.

So you need to download it from Github repositories. It does not matter if his domain is down it is very likely that the developer maintains his release through GitHub which is what Everyone does. Go here and read further:

https://github.com/git-moss/ConvertWithMoss - you can also subscribe and you will get all updates when they are published on GitHub.,

**Comment by saynotohugs** [comment]
Ok now 8 hours after wanting to install ConvertWithMoss I finally managed building the .dmg file - pheeww!
