### ISSUE TITLE
Option to avoid copying the samples

### ISSUE THREAD

**Issue by ensonic** [git-moss/ConvertWithMoss#4]
After running the tool converting from wav to sfz using the same input/output dirs, with "create folder structure" and "add new files" options enabled, I get this result with all the samples copied.
```
> tree a_basses/
a_basses/
├── acid
│   ├── aci_c1.wav
│   ├── aci_c2.wav
│   ├── aci_c3.wav
│   ├── aci_f#1.wav
│   └── aci_f#2.wav
├── acid Samples
│   ├── aci_c1.wav
│   ├── aci_c2.wav
│   ├── aci_c3.wav
│   ├── aci_f#1.wav
│   └── aci_f#2.wav
├── acid.sfz
├── basp
│   ├── was_d#1.wav
│   └── was_g#2.wav
├── basp Samples
│   ├── was_d#1.wav
│   └── was_g#2.wav
├── basp.sfz
...
```
Would it make sens to have an option to reuse the sample folder structure? It would place merged stereo files next to the 'l/r' files and only create the multisamples on level up.

**Comment by ensonic** [comment]
My current workaround is to use a new empty target dir on the same level:
```
Sample-Collection-Foo
Sample-Collection-Foo.sfz
```
and then run the script below

```
#/bin/bash
# replaces 1:1 copies with symlinks
#
# run: ./symlink.sh ./Sample-Collection-Foo.sfz
# verify: find Sample-Collection-Foo.sfz -name "*.wav" -exec ls -al {} \;

if [[ -z "$1" ]]; then
  echo "$0 <sfz dir>"
  exit 1
fi
d=$(realpath $1)

IFS=$'\n'
for f in $(find "$d" -name "*.wav"); do
  o=$(echo "$f" | sed -e 's%\.sfz/%/%' -e 's%\ Samples/%/%')
  if [[ -e "$o" ]]; then
    rm "$f" 
    ln -s "$o" "$f"
  fi
done
```

**Comment by git-moss** [comment]
I always do the copy since I did not want to be blamed for screwing up peoples source files, e.g. when combining mono to stereo. :-)

**Comment by ensonic** [comment]
When converting the result has a new name (without _l/r), but fair enough.
