### ISSUE TITLE
REQ: To add sfz with flac/ogg samples and new format to conversion

### ISSUE THREAD

**Issue by L0w1y** [git-moss/ConvertWithMoss#41]
Please add a new format for sf3/sf4 conversion. These formats are from the soundfont family, only they contain compressed samples. The latter (sf4) is not used anywhere yet.... I also ask you to add the ability to select the type of samples in the source file for the sfz format. It supports not only wav, but also flac, ogg...

**Comment by git-moss** [comment]
The SFZ support can already handle reading files with FLAC and OGG. Do you have files which do not work?

Never heard of sf4. I looked into sf3 but it seems to be it is not used anywhere. Do you have example files?

**Comment by Ivan-Spoda** [comment]
Sf 3 is used, it can be created in all popular soundfont editors, such as Polyphon, Avave Studio, Sfzed... but with the 4th standard, everything is more complicated, it is true that it is almost never used anywhere, I know only one program that uses both sf3 and sf4 - This is Helio Sequencer....
Soundfonts examples: https://drive.google.com/drive/folders/1f-aW1E-yRqAy7E3F6ab2TiExRQyXujkS
(Please note that these sounSf 3 is used, it can be created in all popular soundfont editors, such as Polyphon, Avave Studio, Sfzed... but with the 4th standard, everything is more complicated, it is true that it is almost never used anywhere, I know only one program that uses both sf3 and sf4 - This is Helio Sequencer....
Soundfonts examples: https://drive.google.com/drive/folders/1f-aW1E-yRqAy7E3F6ab2TiExRQyXujkS
(Please note that these soundfonts have been converted to Standards 3 and 4, from Standard 2, using this program: https://github.com/KKQ-KKQ/sf2convert)

**Comment by Ivan-Spoda** [comment]
> The SFZ support can already handle reading files with FLAC and OGG. Do you have files which do not work?
> 
> Never heard of sf4. I looked into sf3 but it seems to be it is not used anywhere. Do you have example files?

Sf 3 is used, it can be created in all popular soundfont editors, such as Polyphon, Avave Studio, Sfzed... but with the 4th standard, everything is more complicated, it is true that it is almost never used anywhere, I know only one program that uses both sf3 and sf4 - This is Helio Sequencer....
Soundfonts examples: https://drive.google.com/drive/folders/1f-aW1E-yRqAy7E3F6ab2TiExRQyXujkS
(Please note that these sounSf 3 is used, it can be created in all popular soundfont editors, such as Polyphon, Avave Studio, Sfzed... but with the 4th standard, everything is more complicated, it is true that it is almost never used anywhere, I know only one program that uses both sf3 and sf4 - This is Helio Sequencer....
Soundfonts examples: https://drive.google.com/drive/folders/1f-aW1E-yRqAy7E3F6ab2TiExRQyXujkS
(Please note that these soundfonts have been converted to Standards 3 and 4, from Standard 2, using this program: https://github.com/KKQ-KKQ/sf2convert)

**Comment by Ivan-Spoda** [comment]
> The SFZ support can already handle reading files with FLAC and OGG. Do you have files which do not work?
> 
> Never heard of sf4. I looked into sf3 but it seems to be it is not used anywhere. Do you have example files?

Sf 3 is used, it can be created in all popular soundfont editors, such as Polyphon, Avave Studio, Sfzed... but with the 4th standard, everything is more complicated, it is true that it is almost never used anywhere, I know only one program that uses both sf3 and sf4 - This is Helio Sequencer....
Soundfonts examples: https://drive.google.com/drive/folders/1f-aW1E-yRqAy7E3F6ab2TiExRQyXujkS
(Please note that these soundfonts have been converted to Standards 3 and 4, from Standard 2, using this program: https://github.com/KKQ-KKQ/sf2convert)

**Comment by git-moss** [comment]
Thanks for the info. Not sure if this will happen but will leave ths issue open for the time being.

**Comment by git-moss** [comment]
After reading through this https://github.com/FluidSynth/fluidsynth/issues/605 I decided not to encourage the use of this/these format(s) in any way. If anyone runs into such files, you can use the sf2convert tool mentioned above to convert it to proper Sf2.
