### ISSUE TITLE
Feature Request [ESX24 support]

### ISSUE THREAD

**Issue by tank-trax** [git-moss/ConvertWithMoss#42]
Could you add ESX24 support?

**Comment by git-moss** [comment]
No, because it is already supported ;-)

**Comment by tank-trax** [comment]
EXS sorry. And thanks.

**Comment by tank-trax** [comment]
As an aside, the Surge Synth Team is in full development mode for the sampler synth Shortcircuit XT. We're looking at parts of your code to implement potential albeit limited EXS24 support. 

If you'd like to drop by and pay us a visit or even lend a hand with development please pay us a visit.

https://discord.gg/fRxJaJJ6

**Comment by git-moss** [comment]
Thanks for getting in touch! I am following the Surge Team developments and check the Discord from time to time.
I am currently not looking for another OSS project ;-)
But I am curious about the state of Shortcircuit XT, is it already usable? Does it have its own multi-sample format and is it documented? If yes, I might be tempted to support it as well :-)

**Comment by tank-trax** [comment]
SC-XT is in an Alpha stage of development. It's usable but still has many bugs. Many features are yet to be implemented. It does have it's own multisample format with .scm as its extension. No documentation (other than the code) as of yet. 

May you succumb to temptation and support it. :-)
