### ISSUE TITLE
Kontakt Compressed NCW Files

### ISSUE THREAD

**Issue by Routhinator** [git-moss/ConvertWithMoss#45]
Hey there, should this support Kontakt Instruments that use `*.ncw` files instead of WAV? 

I've been trying to convert the https://ivyaudio.com/ instruments to Bitwig Multisample and it worked with the SFZ version of the Piano in 162, but the Kontakt version and all the other instruments seem to get stuck. Initially it was erroring out with an Out of Heapspace error, but I passed the required Java params to bump the heap from 8G > 16G. Now, there's no error from convertwithmoss it just seems to sit there crunch through the files and the heap grows until it hits max and then the threads just go idle without an error.

I can't tell if it's a lack of support, or if it really just needs a LOT of working room for NCW conversion.. or maybe it's actually a bug of some kind?

**Comment by Routhinator** [comment]
Nope it was just OOMing again. Looks like it worked with 24g of heap for the Piano.

**Comment by Routhinator** [comment]
I think I understand this now. The application needs 2x the heap for the instrument source size for these conversions, and this was a 6GB input file, and the resulting output was 13 GB, so it needed 6+13GB to work with, plus room for the application and writing streams.

**Comment by git-moss** [comment]
Glad that you could fix it. Can you tell me which configuration you changed since I already set it to 64GB some time ago?!

**Comment by Routhinator** [comment]
Also, since my system is only has 32gb of ram, 64gb would be an invalid heap setting.. no?

**Comment by git-moss** [comment]
Not really, since it grows dynamically. Up to my knowledge the minimum setting is no longer necessary. Need to check if the setting is missing on Linux and Macos.
