### ISSUE TITLE
[Feature Request] Output conversions made from soundfonts to new folders

### ISSUE THREAD

**Issue by audio2000** [git-moss/ConvertWithMoss#47]
Soundfonts are one of the trickiest formats when converting to other instrument formats due to some of their properties.
I created an overview post about this if anyone is interested #49

`ISSUE`
If trying to convert multiple soundfonts that contain multiple banks/patches at the same time, currently all of them get converted into the same folder mixing all of the instruments together so you do not know where they came from.
A good example could be GM soundfonts because  generally contain a minimum of 1 Bank & 128 patches, but could be any soundfonts that contain multiple patches.

`POSSIBLE SOLUTION`
I was thinking, would it be possible to add the following two check box options
1) Create a new folder for each soundfont being converted that has the same name as their filenames and then put the converted instrument outputs into these separate folders.
2) This second option would do the same as above but would only create the folder for each soundfont IF DETECTS that more than 1 instrument is being generated for that soundfont.  Meaning it would NOT create a folder for a soundfont containing only 1 instrument patch, it would just put those instruments in the parent folder.

Wondering if this would be considered and also if any other users would find this useful?
Thank You

Another request I was going to make regarding soundfonts was adding patch numbers as prefixes to instrument names, but another user already did this which can be found here #36.  I think this request goes very well with the request I mentioned in this post.

**Comment by git-moss** [comment]
Uniqueness is already guarenteed. Also clarity is now given with the 2 new options to add the Soundfont name and the preset numbers.
