### ISSUE TITLE
[Feature Request] Allow filename prefixes to conversions made from soundfonts

### ISSUE THREAD

**Issue by audio2000** [git-moss/ConvertWithMoss#48]
Soundfonts are one of the trickiest formats when converting to other instrument formats due to some of their properties.
I created an overview post about this if anyone is interested #49

Currently instruments that get converted from soundfonts to other instrument formats end up getting their patch names as their filenames.  Sometimes patch names are not that great or user wants to know what file that patch name is from.

I was wondering if it would be considered to add a check box option that would do the following.
Add the soundfonts filename as a prefix to the patch name.
So a soundfont named "Great Instruments.sf2" that contained a couple different instrument patches witin it go from generating....
```
piano.sf2
guitar.sf2
bass.sf2
```
to generating...
```
Great Instruments - piano.sf2
Great Instruments - guitar.sf2
Great Instruments - bass.sf2
```
and if the feature mentioned in the following request is added #36 and the check box was checked for that option and this option,  then would generate
```
Great Instruments - 001 - piano.sf2
Great Instruments - 002 - guitar.sf2
Great Instruments - 003 - bass.sf2
```
Thank You

**Comment by git-moss** [comment]
Will be in the next update.
