### ISSUE TITLE
[Feature Request] File naming solutions with conversions made from soundfonts

### ISSUE THREAD

**Issue by audio2000** [git-moss/ConvertWithMoss#49]
I do not think any of this is really going to be added to this application but just sharing some issues I have noticed that all seem to be regarding a similar topic.

Soundfonts are one of the trickiest formats when converting to other instrument formats due to some of their properties.  The properties that I like most about Soundfonts are unfortunately the ones that are the causes of these issues.
Because soundfonts can contain multiple banks that each can contain multiple patches, this can make things very difficult and confusing when having to convert them to other instrument formats because of the file naming that is generated.

If anyone is interested, I have come up with a few ideas to hopefully be able to correct some of these file naming issues.  This is more of an overview kind of post for the following issues mentioned in other posts.
1) Add filename as prefix
#48
2) Add bank/patch number as prefix (Post by another user)
#36
3) Option to place conversions into separate folders 
#47

The following would be added as check box options for user to decide.  Options can be combined to work with each other.
-Add filename as prefix
-Add patch number as prefix
-Add bank number & patch number as prefix
-Place all conversions into separate folders
-Place only conversions that contain more than 1 instrument output, into separate folders

Not sure if any other users would be interested in any of these suggestions?
Hopefully these will be considered to be added to the program.
Thank You

**Comment by git-moss** [comment]
Will take a look at the linked requests.
