### ISSUE TITLE
Application uses up all system memory causing system to freeze

### ISSUE THREAD

**Issue by adrienneteicher** [git-moss/ConvertWithMoss#51]
Hi, I'm trying to convert a Kontakt nki file into a Bitwig multisample but the result is that ConverWithMoss eats up all the system memory until the system freezes.

I tried changing the output format to sfz as an experiment but I had the same outcome.

Macbook Air M1 running on Mac Sonoma 14.7

**Comment by git-moss** [comment]
How large is the input file and how much memory does your Macbook have?

**Comment by adrienneteicher** [comment]
The input file is 57mb and the MacBook Air has 16gb.

Here is a little screen shot of the error message from macos 
![Screenshot 2024-09-20 at 15 57 26](https://github.com/user-attachments/assets/1dbf3c71-3eb7-4701-a07a-6d3145cda6ac)

**Comment by git-moss** [comment]
OK, this looks like a bug. Can you send me an example file?
You can also PM me a download link on KVR.

**Comment by arouax** [comment]
I have the same (or seemingly same) issue when trying to convert from Kontakt to DecentSampler.
I tried it both on Linux and Windows.
The example (source Kontakt file) can be found on Pianobook here (it is free): https://www.pianobook.co.uk/packs/basement-drums/

**Comment by git-moss** [comment]
How much memory does your system have?
In the file "app/ConvertWithMoss.cfg" there is a setting:
java-options=-Xmx64G
Change this to a value lower than your memory, e.g. if you have 16GB do:
java-options=-Xmx16G

**Comment by git-moss** [comment]
Turns out the solution is pretty simple. I do now lazy load the involved WAV files which keeps the memory low. Will be in the next update.
