### ISSUE TITLE
Problem with Ableton format export (Ableton Live 12) / OSX 

### ISSUE THREAD

**Issue by ArekEmplocity** [git-moss/ConvertWithMoss#59]
Hi, I noticed a problem with Ableton export - the exported files didn't load. Live showed very informative error namely : "The preset cannot be loaded". I thought that maybe it's compability with Live 12 and dig a bit deeper.

I found out that there are two problems, that when fixed (with text editor:) fixes the issue and are both sample related:

1. The section:

`			<SampleRef>
							<FileRef>
								<RelativePathType Value="6" />
								<RelativePath Value="Samples/Imported/Acoustic Bass/Acoustic Bass C4.wav" />
								<Path Value="/Volumes/data/Samples/Imported/Acoustic Bass/Acoustic Bass C4.wav" />
								<Type Value="1" />
								<LivePackName Value="" />
								<LivePackId Value="" />
								<OriginalFileSize Value="1223098" />
								
							</FileRef>
`

It provides wrong Path value - not the value of actual User Library but "/Volumes/data" for some reason. Since Ableton format is so stupid, it has to be placed in the particular place to work, perhaps this data should be read from destination folder?

2.  There is also problem with LastModDate:

	`	<LastModDate Value="1732398717866" />`

The value is too big. Ableton doesn't care what the timestamp is, but it needs to be 10 digits and not 13. I will look into source code to check if I can finds any suggestion but I am not really fluent in Java ;)

**Comment by ArekEmplocity** [comment]
Ok, it seems that the timestamp is in milliseconds and Ableton likes it in seconds. I tested only sf2 format.

**Comment by ArekEmplocity** [comment]
I checked the with the MPC keygroup program and have same problem. Also, I tested sf2 file converted with ConvertWithMoss with some supported formats (MPC, SFZ, Tal Sampler, 1010, Decent Sampler) and had same issue.

**Comment by ArekEmplocity** [comment]
Ok, that the problem:

![image](https://github.com/user-attachments/assets/cb84751f-c174-4f23-8318-ab255875a9a0)


Java File object returns time in timestamps by miliseconds, And ableton requires it in seconds. 

so this line:

`  zoneContent = zoneContent.replace ("%SAMPLE_FILE_TIMESTAMP%", Long.toString (sampleFile.lastModified ()));`

Should probably had sampleFile.lastModified () divided by 100.

**Comment by ArekEmplocity** [comment]
Ok, I also see the reason of the second problem, ie in file:

https://github.com/git-moss/ConvertWithMoss/blob/62fae1a0bc23f7eb818bd1411d9e97d48d675475/src/main/resources/de/mossgrabers/convertwithmoss/templates/adv/ADV-MultiSamplePart-Template.xml#L51

the line:

`<Path Value="/Volumes/data/Samples/Imported/%SAMPLE_FOLDER%/%SAMPLE_FILE%" />`

Has hardcoded "/Volumes/data/" path, when in real world it might (and is) different.

**Comment by git-moss** [comment]
Thanks for the analysis! I only have Ableton 11 and just checked again that files load fine both on Windows and Macos.
Therefore, you might be right that they changed something Ableton 12.
The timestamp is easy to fix (will be in the next update).

I am not sure about the path. The 11 library contains all kind of nonsense in there and the file is loaded fine anyway.
Do you get an error that the file is not found or also the "The preset cannot be loaded" message? If they require now a correct path that would mean that all their old libraries will not load and you cannot exchange files between platforms.
Can you check what Ableton write in this parameter when you create a preset in Ableton itself?

**Comment by ArekEmplocity** [comment]
Hi, that's great idea. I turned out that Ableton is writing relative path (like with Unix notation):

![Zrzut ekranu 2024-11-24 o 15 09 27](https://github.com/user-attachments/assets/9a1bac47-d64d-4934-90d1-1c65cee16352)

So I tried if making it relative to the patch file, like in subfolder works, and yes, it works. That way samples can be in the folder as patch file or even in subfolder (like in any sane sample patch format). They don't even need to be in the User Library - they works then from any place on the drive by drag and drop. That seems to be the best way to handle it in my opinion.


![Zrzut ekranu 2024-11-24 o 15 10 52](https://github.com/user-attachments/assets/17b51333-edea-4266-80af-0c9eb6aa1eed)

I attached working simple patch. 

[sam.zip](https://github.com/user-attachments/files/17893619/sam.zip)

**Comment by ArekEmplocity** [comment]
Update:
I've just checked. If the relative path is right and point to the sample, Ableton ignores the Path Value directive. I've just wrote there some random path but the patch still loads up. That's how they maintain compatibility probably.

**Comment by git-moss** [comment]
Oh my, what a mess. Why does it not copy the audio files into its user Samples folder? Sigh.

I just did the same and it generated the following:
<RelativePath Value="Samples/Imported/01W Aftermath/01W Aftermath_ms0_036_c1.wav" />

And this is what I generate as well.

Could it be that you copied the samples manually in the wrong folder? And not the full structure?
Or did they rename the Samples folder to lowercase?
So, what I generate expets in the User-Library the following structure:
Samples/Imported/<Name_of_the_multi-sample>/xxx.wav

**Comment by ArekEmplocity** [comment]
Mos,
I am sorry. I checked once again and the only real problem is with the timestamps. The wrong absolute path is just ignored by Ableton. When I tried converted file but just fixed the lastModifciation timestamp, it works. No need to change the file paths.

**Comment by git-moss** [comment]
Good to hear! The fix for the timestamp is already online.

**Comment by ArekEmplocity** [comment]
Just want to confirm, that new version is working fine :)
