### ISSUE TITLE
EXS24 Conversion Errors - Could not load file: C:/Users/mos/Desktop/filename.dat

### ISSUE THREAD

**Issue by teknologysound** [git-moss/ConvertWithMoss#60]
This error comes up whenever I try to convert an EXS24 file no matter what...I have attempted to run the conversion to several formats and tried it on 2 different Apple computers. That's a Windows directory so I can't imagine that my EXS24 file that I created in Logic is referencing that file

**Comment by git-moss** [comment]
That's some debugging output I forgot to remove. Will be fixed in the next update.
