### ISSUE TITLE
Converting 'Decent Sampler' dspreset

### ISSUE THREAD

**Issue by Axel-Erfurt** [git-moss/ConvertWithMoss#62]
I can't find the error.
What could be wrong here in the file Modern Acoustic Guitar.dspreset?
Maybe someone can help.

The error is:

```
Analyzing: /Daten_HD/Sounds/DecentSampler/Modern Acoustic Guitar V2/Modern Acoustic Guitar.dspreset
Could not load file: Auf Elementtyp "sample" müssen entweder Attributspezifikationen, ">" oder "/>" folgen.
```
`Element type "sample" must be followed by either attribute specifications, ">" or "/>".`

[ModernAcousticGuitar.dspreset.zip](https://github.com/user-attachments/files/17995919/ModernAcousticGuitar.dspreset.zip)

**Comment by git-moss** [comment]
There are spaces missing before several of the "loNote" attributes.
