### ISSUE TITLE
.korgmultisample files not reading

### ISSUE THREAD

**Issue by mega-joe** [git-moss/ConvertWithMoss#64]
I am not able to convert any .korgmultisample files. The files all work fine with Korg Sample Builder 1.2.7 but MOSS reports, "Could not load file: Not an ASCII block." for each file.

Sample file attached (simple oneshot of a single wav file):
[TestKorgMulti.zip](https://github.com/user-attachments/files/18076986/TestKorgMulti.zip)

**Comment by git-moss** [comment]
Seems the format has slightly changed. Need to check in detail...

**Comment by git-moss** [comment]
Will be fixed in the next update.

**Comment by mega-joe** [comment]
Thank you!!
