### ISSUE TITLE
Unsupported file list extended version: 3 error

### ISSUE THREAD

**Issue by MusicMan74** [git-moss/ConvertWithMoss#65]
Hello and thanks for this powerful tool :)

I am trying to convert 'Handbells' to an older version of Kontakt (I have v6).

https://downloads.pianobook.co.uk/Portal%20Downloads/packs/25231_20241122-024740/Handbells.zip
from
https://www.pianobook.co.uk/packs/handbells/

I tried v10.6.0 and v11.5.0 and both give me the following errors with 'Kontakt NKI/NKM' as source and 'Kontakt NKI' as destination:

Analyzing: C:\Users\---\Desktop\Handbells\Handbells - Bell Glass.nki
Detected Kontakt Container format (created with Kontakt 7.10.6.0) - Little-Endian.
Unsupported file list extended version: 3

Analyzing: C:\Users\---\Desktop\Handbells\Handbells - Bounce.nki
Detected Kontakt Container format (created with Kontakt 7.10.6.0) - Little-Endian.
Unsupported file list extended version: 3

(error repeats for all source nki files found...)

What am I doing wrong?

**Comment by git-moss** [comment]
Seems they created a new kind of file list. Let's see how complicated it is...

**Comment by git-moss** [comment]
I think I got it. Will be in the next update.

**Comment by MusicMan74** [comment]
> I think I got it. Will be in the next update.

Thanks! Looking forward to trying it out :)

**Comment by MusicMan74** [comment]
Confirmed that v11.6.0 no longer has this Kontakt-related error. Thanks for a quick response :)
