### ISSUE TITLE
Problem when converting to .xpm

### ISSUE THREAD

**Issue by ShoveD01** [git-moss/ConvertWithMoss#7]
Noticed that the end loop point is the actual sample end not the embedded end loop point.
When converting from .sf2 to .xpm

**Comment by ShoveD01** [comment]
What I’m trying to say is the embedded loop end point becomes the sample end point as far as the Mpc is concerned.

**Comment by git-moss** [comment]
Can you send me the file?

**Comment by ShoveD01** [comment]
Will do , I’m away at the moment, will do it in a couple of days.

**Comment by ShoveD01** [comment]
Hi don’t think I can attach a file to a message through git hub , do you have an email?
Steve

**Comment by git-moss** [comment]
You can attach files here as well. If it is too big just upload it the hoster of your choice and send me a PM.

**Comment by ShoveD01** [comment]
Hopefully attached a soundfont which has a loop end slightly less than the sample end . As you will be able to tell when converted this makes a differences.
Regards Steve




Sent from my iPad

**Comment by ShoveD01** [comment]
﻿
Hi,
Here’s a link to “Flute p.sf2” in my Dropbox:

https://www.dropbox.com/s/20ev7tyvj6xidml/Flute%20p.sf2?dl=0

**Comment by git-moss** [comment]
Thanks. Will have a look.

**Comment by git-moss** [comment]
Seems I did not set the loop end but always the sample end. Will be fixed in the next update.

**Comment by ShoveD01** [comment]
Hi 
thanks that will be great , good work by the way , very useful application, hope you don’t mind another suggestion,  when converting a sf2 bank, in which more than one of the individual instruments references the same sample, the resulting conversion would be much smaller if the all the .xpm files and the samples with original names were all in the same folder. Rather than in separate folders and therefore duplicating the samples. Hope that’s clear.
Regards 
Steve

**Comment by lentferj** [comment]
I tried with latest version (fe4aef7850662fe85d5d9e8bc47f71ffa31d6fbf). It seems that now for converting SFZ to XPM the sample end is always set to "1" when looking at the keygroup with "Program Edit".
[AR DX5 Glitter.sfz.txt](https://github.com/git-moss/ConvertWithMoss/files/7705670/AR.DX5.Glitter.sfz.txt)
[AR DX5 Glitter.xpm.txt](https://github.com/git-moss/ConvertWithMoss/files/7705672/AR.DX5.Glitter.xpm.txt)

**Comment by ShoveD01** [comment]
Hi thanks , but don’t you mean sf2 not sfz?
Steve

**Comment by lentferj** [comment]
No, I mean sfz, sf2 seems to be fine for me. Probably has been introduces in b431c3a4fc296ae3f186c565cfe0fe692678eb83

**Comment by ShoveD01** [comment]
Didn’t you see the problem in the sf2 file I sent?

**Comment by lentferj** [comment]
I think it is a different problem but maybe introduced when fixing what you described for sf2. But @git-moss will have to have a look at it.

**Comment by lentferj** [comment]
Or rather here
https://github.com/git-moss/ConvertWithMoss/commit/fe4aef7850662fe85d5d9e8bc47f71ffa31d6fbf#diff-7a101d5046ded408af644b664f06c5975902ad1e269ee08b593b47700995d301

I assume sampleLoop.getEnd () does return 1 here for some reason.

**Comment by git-moss** [comment]
Could you please send me the audio files as well? Not sure why there is a loop with no end information, might be a broken file or I am missing something.

**Comment by lentferj** [comment]
[AR DX5 Glitter.zip](https://github.com/git-moss/ConvertWithMoss/files/7710868/AR.DX5.Glitter.zip)
sure..

**Comment by lentferj** [comment]
.. and the original SFZ
[AR DX5 Glitter sfz.zip](https://github.com/git-moss/ConvertWithMoss/files/7710888/AR.DX5.Glitter.sfz.zip)

I am quite sure it worked with the older version of the converter ... well, except the looping.

Also, the loop info seems to be there in the single samples - when I open it with "Sample Edit" on my MPC One, the looping is just fine. The info seems to be missing in the keygroup only.

**Comment by ShoveD01** [comment]
Hi just wondering if we are at cross purposes here, my original message referred to sf2 to xpm conversion , and not sfz .
Steve

**Comment by lentferj** [comment]
I tried 9216c0e03693a4ed49814b15d67de2452157f5bb with a few of my non-working examples. Look very good now.. thanks

**Comment by git-moss** [comment]
I also released version 4.5 today, which includes all these fixes.
