### ISSUE TITLE
converted folders/files 

### ISSUE THREAD

**Issue by ShoveD01** [git-moss/ConvertWithMoss#8]
Hi
great work by the way , very useful application, hope you don’t mind another suggestion,  when converting a sf2 bank, in which more than one of the individual instruments references the same sample, the resulting conversion would be much smaller if the all the .xpm files and the samples with original names were all in the same folder. Rather than in separate folders and therefore duplicating the samples. Hope that’s clear.
Regards
Steve

**Comment by git-moss** [comment]
Yeah, I thought about this when implementing it too but decided to go this way since I think this is a bit more flexible in case you want to keep only some of the created instruments and disc space is not really such an issue anymore.

**Comment by ShoveD01** [comment]
Hi all working ok except I noticed that the converted .xpm has the envelope sustain at zero and a very short decay. So the result is a very short blip, until the program is edited in program edit.
Regards 
Steve

**Comment by git-moss** [comment]
There is some guessing involved in the reading/creation of the envelopes, so it might not always be right. Could you send me an example?

**Comment by ShoveD01** [comment]
Hi not the same subject, but noticed the same loop problem occurs when converting from sfz , I.e. it’s looping the whole sample rather than the embedded loop points.
Steve

**Comment by git-moss** [comment]
Please create new issues for individual problems/reports. Currently, only 1 loop is supported.
